# Cloud TiDB Connection
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY
spring.datasource.username=3A4xdYg6ANQH1u6.root
spring.datasource.password=nFoLD1rufcxQiILV

# Hibernate Settings (Automatically creates/updates your tables)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect